import { StripFem } from './build/stripfem.js';
import { StripFem3D } from './build/stripfem3d.js';
import { sliceLoad, kfAt } from './build/strip.js';
const law = { lmnL: 1200e6, lmnM: 0.01, lmnN: 0.255, E: 206e9, nu: 0.3, entryStrain: 0, mu: 0.06, tensionFeedback: true, R: 0.25, Eroll: 206e9, nuRoll: 0.3 };
const nx = +(process.argv[2] ?? 35), nz = +(process.argv[3] ?? 8), ny = +(process.argv[4] ?? 2), mu = +(process.argv[5] ?? 0.06);
const W = 1.0, h0 = 2e-3, h1 = 1.5e-3;
const mk = () => ({ edges: Float64Array.from({ length: nx + 1 }, (_, i) => -W / 2 + (W * i) / nx), h0: new Float64Array(nx), h1: new Float64Array(nx), L: new Float64Array(nx), sigmaB: new Float64Array(nx), sigmaF: new Float64Array(nx) });
const slab = sliceLoad({ ...law, mu }, h0, h1, 50e6, 80e6);
const a = mk();
for (let i = 0; i < nx; i++) { a.h0[i] = h0; a.h1[i] = h1; a.L[i] = slab.arc; a.sigmaB[i] = 50e6; a.sigmaF[i] = 80e6; }
const inp = { ...a, kf: (i, e) => kfAt(law, e), mu, nz, vRoll: 1 };
const f2 = new StripFem(); const t0 = performance.now(); const r2 = f2.solve(inp); const ms2 = performance.now() - t0;
const f3 = new StripFem3D(); const t1 = performance.now(); const r3 = f3.solve({ ...inp, ny }); const ms3 = performance.now() - t1;
const t2 = performance.now(); const r3b = f3.solve({ ...inp, ny }); const ms3b = performance.now() - t2;
const mid = Math.floor(nx / 2);
const show = (name, r, ms) => console.log(`${name}: its ${r.iterations} conv ${r.converged} ${ms.toFixed(0)} ms | q centre ${(r.q[mid]/1e6).toFixed(2)} edge ${(r.q[0]/1e6).toFixed(2)} kN/mm | vIn ${r.vIn.toFixed(4)} vExit ${r.vExit[mid].toFixed(4)} | eps centre ${r.eps[mid].toFixed(4)} edge ${r.eps[0].toFixed(4)} | spread edge ${(r.uExit[0]*1e3).toFixed(1)} mm/s | mass ${r.massRatio.toFixed(4)}`);
console.log(`slab q ${(slab.q/1e6).toFixed(2)} kN/mm, arc ${(slab.arc*1e3).toFixed(1)} mm, ln(h0/h1) ${Math.log(h0/h1).toFixed(4)}`);
show('plane', r2, ms2); show('3D   ', r3, ms3); show('3D warm', r3b, ms3b);
const prof = (r) => { const o = []; for (let j = 0; j < nz; j++) o.push((r.p[mid * nz + j] / 1e6).toFixed(0)); return o.join(' '); };
console.log('p(z) plane:', prof(r2)); console.log('p(z) 3D   :', prof(r3));
